# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  GO_VERSION: 1.23
  PROJECT_NAME: smartpagelist

jobs:

  quality-gate:
    name: Code Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
          check-latest: true

      - name: Static Analysis
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55
          args: --timeout=5m --exclude-use-default=false

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: quality-gate
    strategy:
      matrix:
        go: ['1.23']
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: true
          check-latest: true

      - name: Run Tests
        run: |
          go test -v -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -func=coverage.out
          
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage.out
          flags: unittests
          name: codecov-${{ matrix.go }
